# (Generated by Gemini)

# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /workspace

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.cargo/bin:${PATH}"

# --- Dependency Installation ---
# This is the key change. We copy ONLY the pyproject.toml file.
# Docker caches this layer. If pyproject.toml doesn't change, Docker
# will skip the potentially slow installation step on the next build.
COPY pyproject.toml .

# Install all dependencies, including the 'dev' optional dependencies.
# We use '.[dev]' to specify this. The '.' refers to the current directory project.
# The --system flag tells uv to install into the system's Python environment,
# which is standard practice inside a container.
RUN uv pip install --system --no-cache ".[dev]"

# Copy the rest of your application code
COPY . .

# Command to run the application
# --reload is perfect for the development environment managed by Codespaces/Docker Compose
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
