services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    env_file:
      - path: ./.env.sample
        required: true
      - path: ./.env
        required: false
    depends_on:
      - db

  # "db" is the hostname used in .env
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - path: ./.env.sample
        required: true
      - path: ./.env
        required: false
    ports:
      - "5432:5432"

volumes:
  postgres_data:
